### ISSUE TITLE
Noobquestion

### ISSUE THREAD

**Issue by Lomion-tm** [kotzir/android_kernel_samsung_expressltexx#1]
Is the kernel included in the ROM or do i have to flash ROM +Kernel after one another?

**Comment by kotzir** [comment]
The kernel is necessary for android to boot. It is included in the ROM. If you open the zip you will see a file "boot.img". This is the kernel. The custom one that is uploaded separately has some modifications like overclocking and so on... Hope you understood.

**Comment by Lomion-tm** [comment]
Yes thank you very much :)
